JSFBioShop/src/java/entities/PurchaseOrder.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author ElenaStan
 */
@Entity
@Table(name = "purchase_order")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "PurchaseOrder.findAll", query = "SELECT p FROM PurchaseOrder p"),
    @NamedQuery(name = "PurchaseOrder.findByOrderId", query = "SELECT p FROM PurchaseOrder p WHERE p.orderId = :orderId"),
    @NamedQuery(name = "PurchaseOrder.findByQuantity", query = "SELECT p FROM PurchaseOrder p WHERE p.quantity = :quantity"),
    @NamedQuery(name = "PurchaseOrder.findByShoppingCost", query = "SELECT p FROM PurchaseOrder p WHERE p.shoppingCost = :shoppingCost"),
    @NamedQuery(name = "PurchaseOrder.findBySalesDate", query = "SELECT p FROM PurchaseOrder p WHERE p.salesDate = :salesDate"),
    @NamedQuery(name = "PurchaseOrder.findByShippingDate", query = "SELECT p FROM PurchaseOrder p WHERE p.shippingDate = :shippingDate"),
    @NamedQuery(name = "PurchaseOrder.findByCompany", query = "SELECT p FROM PurchaseOrder p WHERE p.company = :company")})
public class PurchaseOrder implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Column(name = "order_id")
    private Integer orderId;
    @Column(name = "quantity")
    private Integer quantity;
    // @Max(value=?)  @Min(value=?)//if you know range of your decimal fields consider using these annotations to enforce field validation
    @Column(name = "shopping_cost")
    private BigDecimal shoppingCost;
    @Column(name = "sales_date")
    @Temporal(TemporalType.DATE)
    private Date salesDate;
    @Column(name = "shipping_date")
    @Temporal(TemporalType.DATE)
    private Date shippingDate;
    @Size(max = 45)
    @Column(name = "company")
    private String company;
    @JoinColumn(name = "customer_id", referencedColumnName = "customer_id")
    @ManyToOne(optional = false)
    private Customer customerId;
    @JoinColumn(name = "product_id", referencedColumnName = "product_id")
    @ManyToOne(optional = false)
    private Product productId;

    public PurchaseOrder() {
    }

    public PurchaseOrder(Integer orderId) {
        this.orderId = orderId;
    }

    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getShoppingCost() {
        return shoppingCost;
    }

    public void setShoppingCost(BigDecimal shoppingCost) {
        this.shoppingCost = shoppingCost;
    }

    public Date getSalesDate() {
        return salesDate;
    }

    public void setSalesDate(Date salesDate) {
        this.salesDate = salesDate;
    }

    public Date getShippingDate() {
        return shippingDate;
    }

    public void setShippingDate(Date shippingDate) {
        this.shippingDate = shippingDate;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public Customer getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Customer customerId) {
        this.customerId = customerId;
    }

    public Product getProductId() {
        return productId;
    }

    public void setProductId(Product productId) {
        this.productId = productId;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (orderId != null ? orderId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof PurchaseOrder)) {
            return false;
        }
        PurchaseOrder other = (PurchaseOrder) object;
        if ((this.orderId == null && other.orderId != null) || (this.orderId != null && !this.orderId.equals(other.orderId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entities.PurchaseOrder[ orderId=" + orderId + " ]";
    }
    
}

JSFBioShop/src/java/controller/PurchaseOrderController.java
package controller;

import entities.PurchaseOrder;
import controller.util.JsfUtil;
import controller.util.JsfUtil.PersistAction;
import dao.PurchaseOrderFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@ManagedBean(name = "purchaseOrderController")
@SessionScoped
public class PurchaseOrderController implements Serializable {

    @EJB
    private dao.PurchaseOrderFacade ejbFacade;
    private List<PurchaseOrder> items = null;
    private PurchaseOrder selected;

    public PurchaseOrderController() {
    }

    public PurchaseOrder getSelected() {
        return selected;
    }

    public void setSelected(PurchaseOrder selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private PurchaseOrderFacade getFacade() {
        return ejbFacade;
    }

    public PurchaseOrder prepareCreate() {
        selected = new PurchaseOrder();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("resources/Bundle").getString("PurchaseOrderCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("resources/Bundle").getString("PurchaseOrderUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("resources/Bundle").getString("PurchaseOrderDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<PurchaseOrder> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("resources/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("resources/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public List<PurchaseOrder> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<PurchaseOrder> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = PurchaseOrder.class)
    public static class PurchaseOrderControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            PurchaseOrderController controller = (PurchaseOrderController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "purchaseOrderController");
            return controller.getFacade().find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof PurchaseOrder) {
                PurchaseOrder o = (PurchaseOrder) object;
                return getStringKey(o.getOrderId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), PurchaseOrder.class.getName()});
                return null;
            }
        }

    }

}

JSFBioShop/web/purchaseOrder/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PurchaseOrderCreateDlg" widgetVar="PurchaseOrderCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreatePurchaseOrderTitle}">
            <h:form id="PurchaseOrderCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{purchaseOrderController.selected != null}">
                        <p:outputLabel value="#{bundle.CreatePurchaseOrderLabel_orderId}" for="orderId" />
                        <p:inputText id="orderId" value="#{purchaseOrderController.selected.orderId}" title="#{bundle.CreatePurchaseOrderTitle_orderId}" required="true" requiredMessage="#{bundle.CreatePurchaseOrderRequiredMessage_orderId}"/>
                        <p:outputLabel value="#{bundle.CreatePurchaseOrderLabel_quantity}" for="quantity" />
                        <p:inputText id="quantity" value="#{purchaseOrderController.selected.quantity}" title="#{bundle.CreatePurchaseOrderTitle_quantity}" />
                        <p:outputLabel value="#{bundle.CreatePurchaseOrderLabel_shoppingCost}" for="shoppingCost" />
                        <p:inputText id="shoppingCost" value="#{purchaseOrderController.selected.shoppingCost}" title="#{bundle.CreatePurchaseOrderTitle_shoppingCost}" />
                        <p:outputLabel value="#{bundle.CreatePurchaseOrderLabel_salesDate}" for="salesDate" />
                        <p:calendar id="salesDate" pattern="MM/dd/yyyy" value="#{purchaseOrderController.selected.salesDate}" title="#{bundle.EditPurchaseOrderTitle_salesDate}"  showOn="button"/>
                        <p:outputLabel value="#{bundle.CreatePurchaseOrderLabel_shippingDate}" for="shippingDate" />
                        <p:calendar id="shippingDate" pattern="MM/dd/yyyy" value="#{purchaseOrderController.selected.shippingDate}" title="#{bundle.EditPurchaseOrderTitle_shippingDate}"  showOn="button"/>
                        <p:outputLabel value="#{bundle.CreatePurchaseOrderLabel_company}" for="company" />
                        <p:inputText id="company" value="#{purchaseOrderController.selected.company}" title="#{bundle.CreatePurchaseOrderTitle_company}" />
                        <p:outputLabel value="#{bundle.CreatePurchaseOrderLabel_customerId}" for="customerId" />
                        <p:selectOneMenu id="customerId" value="#{purchaseOrderController.selected.customerId}" required="true" requiredMessage="#{bundle.EditPurchaseOrderRequiredMessage_customerId}">
                            <f:selectItems value="#{customerController.itemsAvailableSelectOne}"
                                           var="customerIdItem"
                                           itemValue="#{customerIdItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreatePurchaseOrderLabel_productId}" for="productId" />
                        <p:selectOneMenu id="productId" value="#{purchaseOrderController.selected.productId}" required="true" requiredMessage="#{bundle.EditPurchaseOrderRequiredMessage_productId}">
                            <f:selectItems value="#{productController.itemsAvailableSelectOne}"
                                           var="productIdItem"
                                           itemValue="#{productIdItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{purchaseOrderController.create}" value="#{bundle.Save}" update="display,:PurchaseOrderListForm:datalist,:growl" oncomplete="handleSubmit(args,'PurchaseOrderCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="PurchaseOrderCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

JSFBioShop/web/purchaseOrder/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PurchaseOrderEditDlg" widgetVar="PurchaseOrderEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditPurchaseOrderTitle}">
            <h:form id="PurchaseOrderEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{purchaseOrderController.selected != null}">
                        <p:outputLabel value="#{bundle.EditPurchaseOrderLabel_orderId}" for="orderId" />
                        <p:inputText id="orderId" value="#{purchaseOrderController.selected.orderId}" title="#{bundle.EditPurchaseOrderTitle_orderId}" required="true" requiredMessage="#{bundle.EditPurchaseOrderRequiredMessage_orderId}"/>
                        <p:outputLabel value="#{bundle.EditPurchaseOrderLabel_quantity}" for="quantity" />
                        <p:inputText id="quantity" value="#{purchaseOrderController.selected.quantity}" title="#{bundle.EditPurchaseOrderTitle_quantity}" />
                        <p:outputLabel value="#{bundle.EditPurchaseOrderLabel_shoppingCost}" for="shoppingCost" />
                        <p:inputText id="shoppingCost" value="#{purchaseOrderController.selected.shoppingCost}" title="#{bundle.EditPurchaseOrderTitle_shoppingCost}" />
                        <p:outputLabel value="#{bundle.EditPurchaseOrderLabel_salesDate}" for="salesDate" />
                        <p:calendar id="salesDate" pattern="MM/dd/yyyy" value="#{purchaseOrderController.selected.salesDate}" title="#{bundle.EditPurchaseOrderTitle_salesDate}"  showOn="button"/>
                        <p:outputLabel value="#{bundle.EditPurchaseOrderLabel_shippingDate}" for="shippingDate" />
                        <p:calendar id="shippingDate" pattern="MM/dd/yyyy" value="#{purchaseOrderController.selected.shippingDate}" title="#{bundle.EditPurchaseOrderTitle_shippingDate}"  showOn="button"/>
                        <p:outputLabel value="#{bundle.EditPurchaseOrderLabel_company}" for="company" />
                        <p:inputText id="company" value="#{purchaseOrderController.selected.company}" title="#{bundle.EditPurchaseOrderTitle_company}" />
                        <p:outputLabel value="#{bundle.EditPurchaseOrderLabel_customerId}" for="customerId" />
                        <p:selectOneMenu id="customerId" value="#{purchaseOrderController.selected.customerId}" required="true" requiredMessage="#{bundle.EditPurchaseOrderRequiredMessage_customerId}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{customerController.itemsAvailableSelectOne}"
                                           var="customerIdItem"
                                           itemValue="#{customerIdItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditPurchaseOrderLabel_productId}" for="productId" />
                        <p:selectOneMenu id="productId" value="#{purchaseOrderController.selected.productId}" required="true" requiredMessage="#{bundle.EditPurchaseOrderRequiredMessage_productId}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{productController.itemsAvailableSelectOne}"
                                           var="productIdItem"
                                           itemValue="#{productIdItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{purchaseOrderController.update}" value="#{bundle.Save}" update="display,:PurchaseOrderListForm:datalist,:growl" oncomplete="handleSubmit(args, 'PurchaseOrderEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="PurchaseOrderEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

JSFBioShop/web/purchaseOrder/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListPurchaseOrderTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="PurchaseOrderListForm">
                <p:panel header="#{bundle.ListPurchaseOrderTitle}">
                    <p:dataTable id="datalist" value="#{purchaseOrderController.items}" var="item"
                                 selectionMode="single" selection="#{purchaseOrderController.selected}"
                                 paginator="true"
                                 rowKey="#{item.orderId}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPurchaseOrderTitle_orderId}"/>
                            </f:facet>
                            <h:outputText value="#{item.orderId}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPurchaseOrderTitle_quantity}"/>
                            </f:facet>
                            <h:outputText value="#{item.quantity}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPurchaseOrderTitle_shoppingCost}"/>
                            </f:facet>
                            <h:outputText value="#{item.shoppingCost}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPurchaseOrderTitle_salesDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.salesDate}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPurchaseOrderTitle_shippingDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.shippingDate}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPurchaseOrderTitle_company}"/>
                            </f:facet>
                            <h:outputText value="#{item.company}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPurchaseOrderTitle_customerId}"/>
                            </f:facet>
                            <h:outputText value="#{item.customerId}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPurchaseOrderTitle_productId}"/>
                            </f:facet>
                            <h:outputText value="#{item.productId}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{purchaseOrderController.prepareCreate}" update=":PurchaseOrderCreateForm" oncomplete="PF('PurchaseOrderCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":PurchaseOrderViewForm" oncomplete="PF('PurchaseOrderViewDialog').show()" disabled="#{empty purchaseOrderController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":PurchaseOrderEditForm" oncomplete="PF('PurchaseOrderEditDialog').show()" disabled="#{empty purchaseOrderController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{purchaseOrderController.destroy}" update=":growl,datalist" disabled="#{empty purchaseOrderController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

JSFBioShop/web/purchaseOrder/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PurchaseOrderViewDlg" widgetVar="PurchaseOrderViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewPurchaseOrderTitle}">
            <h:form id="PurchaseOrderViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{purchaseOrderController.selected != null}">
                        <h:outputText value="#{bundle.ViewPurchaseOrderLabel_orderId}"/>
                        <h:outputText value="#{purchaseOrderController.selected.orderId}" title="#{bundle.ViewPurchaseOrderTitle_orderId}"/>
                        <h:outputText value="#{bundle.ViewPurchaseOrderLabel_quantity}"/>
                        <h:outputText value="#{purchaseOrderController.selected.quantity}" title="#{bundle.ViewPurchaseOrderTitle_quantity}"/>
                        <h:outputText value="#{bundle.ViewPurchaseOrderLabel_shoppingCost}"/>
                        <h:outputText value="#{purchaseOrderController.selected.shoppingCost}" title="#{bundle.ViewPurchaseOrderTitle_shoppingCost}"/>
                        <h:outputText value="#{bundle.ViewPurchaseOrderLabel_salesDate}"/>
                        <h:outputText value="#{purchaseOrderController.selected.salesDate}" title="#{bundle.ViewPurchaseOrderTitle_salesDate}">
                            <f:convertDateTime pattern="MM/dd/yyyy" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewPurchaseOrderLabel_shippingDate}"/>
                        <h:outputText value="#{purchaseOrderController.selected.shippingDate}" title="#{bundle.ViewPurchaseOrderTitle_shippingDate}">
                            <f:convertDateTime pattern="MM/dd/yyyy" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewPurchaseOrderLabel_company}"/>
                        <h:outputText value="#{purchaseOrderController.selected.company}" title="#{bundle.ViewPurchaseOrderTitle_company}"/>
                        <h:outputText value="#{bundle.ViewPurchaseOrderLabel_customerId}"/>
                        <h:outputText value="#{purchaseOrderController.selected.customerId}" title="#{bundle.ViewPurchaseOrderTitle_customerId}"/>
                        <h:outputText value="#{bundle.ViewPurchaseOrderLabel_productId}"/>
                        <h:outputText value="#{purchaseOrderController.selected.productId}" title="#{bundle.ViewPurchaseOrderTitle_productId}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="PurchaseOrderViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>